# Form implementation generated from reading ui file 'App_Master.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtWidgets import QMenu
import sys
from datetime import *
from UserEdit_Menu import Ui_EditUser_Menu
from QueryTableChanges_Window import Ui_QueryTableChanges_Window
from PasswordEdit_Window import Ui_EditPasswordWindow
from config import get_path



class Ui_App_Master(object):
    """
    Main application window for the admin app.
    """
    def __init__(self, name, username):
        """
        Initializes the main window, setting up the user interface and storing user-specific details.

        Args:
            name (str): The name of the user.
            username (str): The username of the user.
        """
        self.name=name
        self.username=username


    def setupUi(self, App_Master):
        """
        Sets up the user interface components for the main application window.

        Args:
            App_Master (QtWidgets.QMainWindow): The main window object to set up.
        """
        App_Master.setObjectName("App_Master")
        App_Master.resize(1254, 860)
        App_Master.setMinimumSize(QtCore.QSize(945, 860))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(str(get_path("Resources", "Iconos", "icon.ico"))), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        App_Master.setWindowIcon(icon)
        App_Master.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=App_Master)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.FrameApp = QtWidgets.QVBoxLayout()
        self.FrameApp.setObjectName("FrameApp")
        self.Header = QtWidgets.QHBoxLayout()
        self.Header.setContentsMargins(-1, 0, -1, -1)
        self.Header.setObjectName("Header")
        self.LogoIcon = QtWidgets.QLabel(parent=self.frame)
        self.LogoIcon.setMinimumSize(QtCore.QSize(220, 52))
        self.LogoIcon.setMaximumSize(QtCore.QSize(220, 52))
        self.LogoIcon.setText("")
        self.LogoIcon.setPixmap(QtGui.QPixmap(str(get_path("Resources", "Iconos", "Logo.ico"))))
        self.LogoIcon.setScaledContents(True)
        self.LogoIcon.setObjectName("LogoIcon")
        self.Header.addWidget(self.LogoIcon)
        spacerItem = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.Header.addItem(spacerItem)
        self.Button_Users = QtWidgets.QPushButton(parent=self.frame)
        self.Button_Users.setMinimumSize(QtCore.QSize(50, 50))
        self.Button_Users.setMaximumSize(QtCore.QSize(50, 50))
        self.Button_Users.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Button_Users.setStyleSheet("QPushButton{\n"
"    border: 1px solid transparent;\n"
"    border-color: rgb(3, 174, 236);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 1px solid transparent;\n"
"    border-color: rgb(0, 0, 0);\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 1px solid transparent;\n"
"    border-color: rgb(0, 0, 0);\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgb(200, 200, 200);\n"
"    border-radius: 10px;\n"
"}")
        self.Button_Users.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(str(get_path("Resources", "Iconos", "User_Edit.png"))), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Button_Users.setIcon(icon1)
        self.Button_Users.setIconSize(QtCore.QSize(40, 40))
        self.Button_Users.setObjectName("Button_Users")
        self.Header.addWidget(self.Button_Users)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.Header.addItem(spacerItem1)
        self.Button_DBChanges = QtWidgets.QPushButton(parent=self.frame)
        self.Button_DBChanges.setMinimumSize(QtCore.QSize(50, 50))
        self.Button_DBChanges.setMaximumSize(QtCore.QSize(50, 50))
        self.Button_DBChanges.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Button_DBChanges.setStyleSheet("QPushButton{\n"
"    border: 1px solid transparent;\n"
"    border-color: rgb(3, 174, 236);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 1px solid transparent;\n"
"    border-color: rgb(0, 0, 0);\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 1px solid transparent;\n"
"    border-color: rgb(0, 0, 0);\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgb(200, 200, 200);\n"
"    border-radius: 10px;\n"
"}")
        self.Button_DBChanges.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(str(get_path("Resources", "Iconos", "Database_Changes.png"))), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Button_DBChanges.setIcon(icon4)
        self.Button_DBChanges.setIconSize(QtCore.QSize(40, 40))
        self.Button_DBChanges.setObjectName("Button_DBChanges")
        self.Header.addWidget(self.Button_DBChanges)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.Header.addItem(spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.Header.addItem(spacerItem5)
        self.HeaderName = QtWidgets.QLabel(parent=self.frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.HeaderName.setFont(font)
        self.HeaderName.setStyleSheet("color:rgb(3, 174, 236)")
        self.HeaderName.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.HeaderName.setObjectName("HeaderName")
        self.Header.addWidget(self.HeaderName)
        spacerItem6 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.Header.addItem(spacerItem6)
        self.Button_Profile = QtWidgets.QPushButton(parent=self.frame)
        self.Button_Profile.setMinimumSize(QtCore.QSize(50, 50))
        self.Button_Profile.setMaximumSize(QtCore.QSize(50, 50))
        self.Button_Profile.setStyleSheet("QPushButton{\n"
"    border: 1px solid transparent;\n"
"    border-color: rgb(3, 174, 236);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 1px solid transparent;\n"
"    border-color: rgb(0, 0, 0);\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 1px solid transparent;\n"
"    border-color: rgb(0, 0, 0);\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgb(200, 200, 200);\n"
"    border-radius: 10px;\n"
"}")
        self.Button_Profile.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(str(get_path("Resources", "Iconos", "User.png"))), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Button_Profile.setIcon(icon6)
        self.Button_Profile.setIconSize(QtCore.QSize(40, 40))
        self.Button_Profile.setObjectName("Button_Profile")
        self.Header.addWidget(self.Button_Profile)
        self.FrameApp.addLayout(self.Header)
        spacerItem7 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.FrameApp.addItem(spacerItem7)
        self.PrincipalScreen = QtWidgets.QHBoxLayout()
        self.PrincipalScreen.setObjectName("PrincipalScreen")
        self.ButtonFrame = QtWidgets.QFrame(parent=self.frame)
        self.ButtonFrame.setMinimumSize(QtCore.QSize(220, 0))
        self.ButtonFrame.setMaximumSize(QtCore.QSize(220, 16777215))
        self.ButtonFrame.setAutoFillBackground(False)
        self.ButtonFrame.setStyleSheet("QFrame{\n"
"    background-color: rgb(3, 174, 236);\n"
"}\n"
"\n"
"QPushButton{\n"
"    border: 1px solid transparent;\n"
"    color: rgb(3, 174, 236);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    border: 1px solid transparent;\n"
"    border-color: rgb(0, 0, 0);\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border: 1px solid transparent;\n"
"    border-color: rgb(0, 0, 0);\n"
"    color: rgb(0,0,0);\n"
"    background-color: rgb(200, 200, 200);\n"
"    border-radius: 10px;\n"
"}")
        self.ButtonFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.ButtonFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.ButtonFrame.setObjectName("ButtonFrame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.ButtonFrame)
        self.verticalLayout_3.setContentsMargins(9, 0, -1, 0)
        self.verticalLayout_3.setSpacing(25)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Button_Commercial = QtWidgets.QPushButton(parent=self.ButtonFrame)
        self.Button_Commercial.setMinimumSize(QtCore.QSize(200, 50))
        self.Button_Commercial.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.Button_Commercial.setFont(font)
        self.Button_Commercial.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Button_Commercial.setObjectName("Button_Commercial")
        self.verticalLayout_3.addWidget(self.Button_Commercial)
        self.Button_Technical = QtWidgets.QPushButton(parent=self.ButtonFrame)
        self.Button_Technical.setMinimumSize(QtCore.QSize(200, 50))
        self.Button_Technical.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.Button_Technical.setFont(font)
        self.Button_Technical.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Button_Technical.setObjectName("Button_Technical")
        self.verticalLayout_3.addWidget(self.Button_Technical)
        self.Button_Purchasing = QtWidgets.QPushButton(parent=self.ButtonFrame)
        self.Button_Purchasing.setMinimumSize(QtCore.QSize(200, 50))
        self.Button_Purchasing.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.Button_Purchasing.setFont(font)
        self.Button_Purchasing.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Button_Purchasing.setObjectName("Button_Purchasing")
        self.verticalLayout_3.addWidget(self.Button_Purchasing)
        self.Button_Invoicing = QtWidgets.QPushButton(parent=self.ButtonFrame)
        self.Button_Invoicing.setMinimumSize(QtCore.QSize(200, 50))
        self.Button_Invoicing.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.Button_Invoicing.setFont(font)
        self.Button_Invoicing.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Button_Invoicing.setObjectName("Button_Invoicing")
        self.verticalLayout_3.addWidget(self.Button_Invoicing)
        self.Button_Workshop = QtWidgets.QPushButton(parent=self.ButtonFrame)
        self.Button_Workshop.setMinimumSize(QtCore.QSize(200, 50))
        self.Button_Workshop.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.Button_Workshop.setFont(font)
        self.Button_Workshop.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Button_Workshop.setObjectName("Button_Workshop")
        self.verticalLayout_3.addWidget(self.Button_Workshop)
        self.Button_Warehouse = QtWidgets.QPushButton(parent=self.ButtonFrame)
        self.Button_Warehouse.setMinimumSize(QtCore.QSize(200, 50))
        self.Button_Warehouse.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.Button_Warehouse.setFont(font)
        self.Button_Warehouse.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Button_Warehouse.setObjectName("Button_Warehouse")
        self.verticalLayout_3.addWidget(self.Button_Warehouse)
        self.Button_Verification = QtWidgets.QPushButton(parent=self.ButtonFrame)
        self.Button_Verification.setMinimumSize(QtCore.QSize(200, 50))
        self.Button_Verification.setMaximumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.Button_Verification.setFont(font)
        self.Button_Verification.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.Button_Verification.setObjectName("Button_Verification")
        self.verticalLayout_3.addWidget(self.Button_Verification)
        self.PrincipalScreen.addWidget(self.ButtonFrame)
        spacerItem8 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.PrincipalScreen.addItem(spacerItem8)
        self.MainLayout = QtWidgets.QVBoxLayout()
        self.MainLayout.setObjectName("MainLayout")
        self.tableMaster = QtWidgets.QTableWidget(parent=self.frame)
        self.tableMaster.setMinimumSize(QtCore.QSize(650, 280))
        self.tableMaster.setObjectName("tableMaster")
        self.tableMaster.setColumnCount(0)
        self.tableMaster.setRowCount(0)
        self.tableMaster.verticalHeader().setVisible(False)
        self.MainLayout.addWidget(self.tableMaster)
        spacerItem9 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.MainLayout.addItem(spacerItem9)
        self.BottomLayout = QtWidgets.QHBoxLayout()
        self.BottomLayout.setContentsMargins(-1, 0, -1, -1)
        self.BottomLayout.setObjectName("BottomLayout")
        self.MainLayout.addLayout(self.BottomLayout)
        self.PrincipalScreen.addLayout(self.MainLayout)
        self.FrameApp.addLayout(self.PrincipalScreen)
        self.gridLayout.addLayout(self.FrameApp, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        App_Master.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=App_Master)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1254, 22))
        self.menubar.setObjectName("menubar")
        App_Master.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=App_Master)
        self.statusbar.setObjectName("statusbar")
        App_Master.setStatusBar(self.statusbar)

        self.retranslateUi(App_Master)
        QtCore.QMetaObject.connectSlotsByName(App_Master)

        self.Button_Commercial.clicked.connect(self.commercial_app)
        self.Button_Technical.clicked.connect(self.technical_app)
        self.Button_Purchasing.clicked.connect(self.purchasing_app)
        self.Button_Invoicing.clicked.connect(self.invoicing_app)
        self.Button_Workshop.clicked.connect(self.workshop_app)
        self.Button_Warehouse.clicked.connect(self.warehouse_app)
        self.Button_Verification.clicked.connect(self.verification_app)
        self.Button_Users.clicked.connect(self.user_edition)
        self.Button_DBChanges.clicked.connect(self.dbchanges)
        self.Button_Profile.clicked.connect(self.showMenu)

# Function to translate and updates the text of various UI elements
    def retranslateUi(self, App_Master):
        """
        Translates and updates the text of various UI elements in the given App_Comercial.
        """
        _translate = QtCore.QCoreApplication.translate
        App_Master.setWindowTitle(_translate("App_Master", "ERP EIPSA"))
        self.Button_Users.setToolTip(_translate("App_Master", "Editar Usuarios"))
        self.Button_DBChanges.setToolTip(_translate("App_Master", "Tablas De Cambios"))
        self.HeaderName.setText(_translate("App_Master", self.name))
        self.Button_Commercial.setText(_translate("App_Master", "Comercial"))
        self.Button_Technical.setText(_translate("App_Master", "Técnico"))
        self.Button_Purchasing.setText(_translate("App_Master", "Compras"))
        self.Button_Invoicing.setText(_translate("App_Master", "Facturación"))
        self.Button_Workshop.setText(_translate("App_Master", "Taller"))
        self.Button_Warehouse.setText(_translate("App_Master", "Almacén"))
        self.Button_Verification.setText(_translate("App_Master", "Verificación"))

    def commercial_app(self):
        """
        Opens the commercial application window.
        """
        from App_Comercial import Ui_App_Comercial
        self.commercial_window = Ui_App_Comercial('Ana Calvo', 'a.calvo')
        self.commercial_window.showMaximized()

    def technical_app(self):
        """
        Opens the technical application window.
        """
        from App_Technical import Ui_App_Technical
        self.technical_window = Ui_App_Technical('Jorge Valtierra', 'j.valtierra')
        self.technical_window.showMaximized()

    def purchasing_app(self):
        """
        Opens the purchasing application window.
        """
        from App_Purchasing import Ui_App_Purchasing
        self.purchasing_window = QtWidgets.QMainWindow()
        self.ui_purchase = Ui_App_Purchasing('Daniel Marquez', 'd.marquez')
        self.ui_purchase.setupUi(self.purchasing_window)
        self.purchasing_window.showMaximized()

    def invoicing_app(self):
        """
        Opens the invoicing application window.
        """
        from App_Invoicing import Ui_App_Invoicing
        self.invoicing_window = QtWidgets.QMainWindow()
        self.ui_invoice = Ui_App_Invoicing('Miguel Sahuquillo', 'm.sahuquillo')
        self.ui_invoice.setupUi(self.invoicing_window)
        self.invoicing_window.showMaximized()

    def workshop_app(self):
        """
        Opens the workshop application window.
        """
        from App_Workshop import Ui_App_Workshop
        self.workshop_window = QtWidgets.QMainWindow()
        self.ui_workshop = Ui_App_Workshop('Julio Zofio', 'j.zofio')
        self.ui_workshop.setupUi(self.workshop_window)
        self.workshop_window.showMaximized()

    def warehouse_app(self):
        """
        Opens the warehouse application window.
        """
        from App_Warehouse import Ui_App_Warehouse
        self.warehouse_window = QtWidgets.QMainWindow()
        self.ui_warehouse = Ui_App_Warehouse('Juan Tena', 'j.tena')
        self.ui_warehouse.setupUi(self.warehouse_window)
        self.warehouse_window.showMaximized()

    def verification_app(self):
        """
        Opens the verification application window.
        """
        from App_Verification import Ui_App_Verification
        self.verif_window = QtWidgets.QMainWindow()
        self.ui_verification = Ui_App_Verification('Mario Gil', 'm.gil')
        self.ui_verification.setupUi(self.verif_window)
        self.verif_window.showMaximized()

    def user_edition(self):
        """
        Opens the user edition window.
        """
        self.edit_user_menu=QtWidgets.QMainWindow()
        self.ui=Ui_EditUser_Menu()
        self.ui.setupUi(self.edit_user_menu)
        self.edit_user_menu.show()

    def dbchanges(self):
        """
        Opens the database changes window.
        """
        self.tableschanges_menu=QtWidgets.QMainWindow()
        self.ui=Ui_QueryTableChanges_Window()
        self.ui.setupUi(self.tableschanges_menu)
        self.tableschanges_menu.show()

    def showMenu(self):
        """
        Displays a context menu when the profile button is clicked. 
        Provides options to edit the password.
        """
        menu = QMenu(self.centralwidget)
        menu.setStyleSheet("QMenu { border: 1px solid black; width: 125px; right: -1px; }"
        "QMenu::item:selected { background-color: rgb(3, 174, 236); color: white; }")
        option1 = menu.addAction("Editar contraseña")
        option1.triggered.connect(lambda: self.editpassword())
        menu.addAction(option1)
        button = self.Button_Profile
        menu.exec(button.mapToGlobal(QtCore.QPoint(-75, 50)))

    def editpassword(self):
        """
        Opens a new window for editing the user's password. 
        """
        self.edit_password_window=QtWidgets.QMainWindow()
        self.ui=Ui_EditPasswordWindow(self.username)
        self.ui.setupUi(self.edit_password_window)
        self.edit_password_window.show()



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    App_Master = QtWidgets.QMainWindow()
    ui = Ui_App_Master('Enrique Serrano', 'e.serrano')
    ui.setupUi(App_Master)
    App_Master.show()
    sys.exit(app.exec())
